Repository FRONTENDSCHOOL10/Pisa-s-4top, pull requests merged in 2024-09, with the labels that each got.

#22 setting(#14): 라우터 세팅
  src/App.tsx
Labels: ⚙ Settings

#24 feat(#23): 스토리북 설치
  .eslintrc.js
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  package.json
  pnpm-lock.yaml
  src/stories/RecommendTeaCard.stories.ts
Labels: 📃 Docs, ✨ Feature

#25 feat(#18): 버튼 컴포넌트 구현 및 색상 코드 추가
  src/components/Buttons/Buttons.tsx
  tailwind.config.js
Labels: 🎨 HTML&CSS

#28 setting: flaticon import 구문 추가
  src/styles/globals.css
Labels: ⚙ Settings

#29 design: 색상 값 수정
  src/components/Buttons/Buttons.tsx
  tailwind.config.js
Labels: ⚜️Design

#30 feat(#12): 티 추천 카드 스와이퍼 컴포넌트 작업 및 스토리북 컴포넌트 추가
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/components/Button.tsx
  src/components/TeaCard/TeaRecommendCard.tsx
  src/components/TeaCard/TeaRecommendSwiper.tsx
  src/stories/Buttons.stories.tsx
  src/stories/RecommendTeaCard.stories.ts
  src/stories/TeaRecommendCard.stories.tsx
  src/styles/globals.css
  src/styles/icons.css
  vite.config.js
Labels: 🐞 BugFix, ✨ Feature, ⚜️Design, 🎨 HTML&CSS

#33 feat(#32/#15): 내비게이션 컴포넌트, 버그수정
  src/components/BottomNav.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Recommend/TeaListPage.tsx
  src/pages/Reviews/ReviewsPage.tsx
  src/pages/Settings/MyPage.tsx
  src/styles/fonts.css
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor, ⚜️Design, 🎨 HTML&CSS

#36 feat(#17): 로고 컴포넌트 작업
  public/assets/totd-logo.svg
  public/assets/typeLogo-lg.svg
  public/assets/typeLogo-sm.svg
  src/components/Logo.tsx
Labels: ✨ Feature, ⚜️Design

#39 chore(38): 패키지 설치/제거
  package.json
  pnpm-lock.yaml
  src/main.tsx
Labels: ⚙ Settings

#40 feat(#37): 티 리뷰 카드 컴포넌트 작업 및 타 카드 리팩토링
  public/assets/starRate.css
  public/assets/starRate.webp
  src/components/TeaCard/TeaDescriptionCard.tsx
  src/components/TeaCard/TeaRecommendSwiper.tsx
  src/components/TeaCard/TeaReviewCard.tsx
  src/stories/TeaCard.stories.tsx
  src/styles/globals.css
Labels: ⚜️Design, 🎨 HTML&CSS

#42 feat: 라벨 컴포넌트 구현
  src/components/Labels/Labels.tsx
  src/stories/Labels.stories.tsx
Labels: 🎨 HTML&CSS

#44 feat(#43): 내비게이션 컴포넌트 리팩토링 & 테일윈드 레이어 추가
  src/components/BottomNav.tsx
  src/styles/globals.css
Labels: ⚙ Settings, 🔨 Refactor, 🥰 Accessibility

#46 feat(#41/#45): 레시피 카드 컴포넌트 및 찜 버튼 구현
  src/components/Buttons/Buttons.tsx
  src/components/TeaCard/TeaRecipeCard.tsx
  src/components/TeaCard/TeaRecommendCard.tsx
  src/stories/Buttons.stories.tsx
  src/stories/TeaCard.stories.tsx
Labels: 🎨 HTML&CSS

#48 feat(11): checkbox 컴포넌트 마크업
  src/components/Input/CheckBox.tsx
Labels: 🎨 HTML&CSS

#47 feat(10): input 컴포넌트 마크업
  src/components/Input/Input.tsx
  src/components/Input/SearchInput.tsx
  src/styles/fonts.css
Labels: 🎨 HTML&CSS

#49 feat(#13): App Bar 컴포넌트 작업
  src/components/AppBar.tsx
Labels: ✨ Feature, ⚜️Design, 🎨 HTML&CSS

#52 refactor(#51): 리스트 피드백 반영
  src/components/TeaCard/TeaRecipeCard.tsx
Labels: 🔨 Refactor

#55 refactor(#54): 경로 오류 수정
  src/styles/globals.css
Labels: 🔨 Refactor

#56 refactor(#53): 스토리북 피드백 반영 수정
  src/stories/Buttons.stories.tsx
  src/stories/Labels.stories.tsx
  src/stories/TeaCard.stories.tsx
Labels: 🔨 Refactor

#58 docs(50): storybook 문서 작성
  src/components/Input/SearchInput.tsx
  src/stories/CheckBox.stories.tsx
  src/stories/Input.stories.tsx
Labels: 📃 Docs

#60 feat(#59):AppBar, BottomNav, Logo 스토리북 작성
  src/App.tsx
  src/components/AppBar.tsx
  src/components/Logo.tsx
  src/stories/AppBar.stories.tsx
  src/stories/BottomNav.stories.tsx
  src/stories/Logo.stories.tsx
Labels: ✅ Test, ⚒️ Modify

#61 docs(#57): 티 카드 스토리북 레시피 카드 추가
  src/stories/TeaCard.stories.tsx
Labels: 📃 Docs

#63 feat(#62): 버튼 컴포넌트 hover 기능 추가
  src/components/Buttons/Buttons.tsx
Labels: 🎨 HTML&CSS

#66 docs(#64): 버튼 스토리북 하트 버튼 컴포넌트 추가
  src/stories/Buttons.stories.tsx
Labels: 📃 Docs

#77 refactor(#76): 스토리북 스토리 코드 수정
  src/stories/TeaCard.stories.tsx
  src/styles/globals.css
  src/styles/starRate.css
Labels: 🔨 Refactor

#78 refactor(#74): aria-label 추가 및 코드 리팩토링
  src/components/BottomNav.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Recommend/TeaListPage.tsx
  src/pages/Reviews/ReviewsPage.tsx
  src/pages/Settings/MyPage.tsx
Labels: 🔨 Refactor, ⚒️ Modify

#79 feat(#21): 홈 리뷰 카드 컴포넌트
  src/components/Review/HomeReviewCard.tsx
  tailwind.config.js
Labels: 🎨 HTML&CSS

#80 refactor(70): 타입 명시
  src/components/Input/Input.tsx
  src/components/Input/SearchInput.tsx
  src/main.tsx
Labels: 🔨 Refactor

#82 refactor(#81/#76): 티 카드 컴포넌트 리팩토링 및 스토리북 스토리 코드 8버전으로 업데이트
  .storybook/main.ts
  src/components/TeaCard/TeaDescriptionCard.tsx
  src/components/TeaCard/TeaRecipeCard.tsx
  src/components/TeaCard/TeaRecommendCard.tsx
  src/components/TeaCard/TeaRecommendSwiper.tsx
  src/components/TeaCard/TeaReviewCard.tsx
  src/stories/AppBar.stories.tsx
  src/stories/BottomNav.stories.tsx
  src/stories/Buttons.stories.tsx
  src/stories/CheckBox.stories.tsx
  src/stories/Input.stories.tsx
  src/stories/Labels.stories.tsx
  src/stories/SearchInput.stories.tsx
  src/stories/TeaCard.stories.tsx
  src/stories/TeaCard/TeaDescriptionCard.stories.tsx
  src/stories/TeaCard/TeaRecipeCard.stories.tsx
  src/stories/TeaCard/TeaRecommendCard.stories.tsx
  src/stories/TeaCard/TeaRecommendSwiper.stories.tsx
  src/stories/TeaCard/TeaReviewCard.stories.tsx
Labels: 🔨 Refactor

#84 refactor(#72): 로고 컴포넌트 리팩토링
  src/components/Logo.tsx
Labels: 🔨 Refactor

#86 refactor(#85): utils/createUrl.ts 생성
  src/components/Logo.tsx
  src/utils/createUrl.ts
Labels: 🔨 Refactor

#88 refactor(#87): 별점 스프라이트 svg로 수정
  public/assets/starRate.svg
  public/assets/starRate.webp
  src/components/Review/StarRate.tsx
  src/components/TeaCard/TeaReviewCard.tsx
  src/styles/globals.css
  src/styles/starRate.css
Labels: 🔨 Refactor

#90 feat(#89): 홈 리뷰 카드 스토리 추가
  src/components/Review/HomeReviewCard.tsx
  src/stories/TeaCard/HomeReviewCard.stories.tsx
  src/stories/TeaCard/TeaDescriptionCard.stories.tsx
  src/stories/TeaCard/TeaRecipeCard.stories.tsx
  src/stories/TeaCard/TeaRecommendCard.stories.tsx
  src/stories/TeaCard/TeaRecommendSwiper.stories.tsx
  src/stories/TeaCard/TeaReviewCard.stories.tsx
Labels: ✨ Feature

#91 refactor(#67): index 타이틀 수정
  index.html
Labels: 🥰 Accessibility

#92 refactor(#68): Suspense, lazy 추가
  src/App.tsx
Labels: 🔨 Refactor

#93 refactor(#20): 요소 컴포넌트로 변경
  src/components/Review/StarRate.tsx
  src/components/TeaCard/TeaReviewCard.tsx
Labels: 🔨 Refactor

#94 refactor(#71): Label 컴포넌트 피드백 반영 수정
  src/components/Labels/Labels.tsx
Labels: 🔨 Refactor

#98 refactor(#97): 라벨 컴포넌트 스토리북 수정
  src/stories/Labels.stories.tsx
Labels: 🔨 Refactor

#96 refactor: useId() 훅 사용
  src/components/Input/CheckBox.tsx
  src/components/Input/Input.tsx
  src/components/Input/SearchInput.tsx
Labels: 🔨 Refactor

#99 design(#95): 홈 리뷰 컴포넌트 스타일링 수정 및 스토리북 수정
  src/components/Review/HomeReviewCard.tsx
  src/stories/TeaCard/HomeReviewCard.stories.tsx
Labels: 🔨 Refactor, ⚜️Design

#102 feat(#101): 수색 선택 컴포넌트 마크업
  src/components/Input/SelectColor.tsx
  src/stories/SelectColor.stories.tsx
Labels: 🎨 HTML&CSS

#104 modify: 앱 상단바 디테일 수정
  src/components/AppBar.tsx
  src/components/Logo.tsx
Labels: 🔨 Refactor, ⚒️ Modify

#105 modify: 하단 내비 디테일 수정
  src/components/BottomNav.tsx
Labels: ⚒️ Modify

#107 refactor(#106): app.tsx 리팩토링
  src/App.tsx
  src/pages/Join/index.ts
  src/pages/Main/index.ts
  src/pages/Recommend/index.ts
  src/pages/Reviews/ReviewsPage.tsx
  src/pages/Reviews/index.ts
  src/pages/Settings/index.ts
  src/pages/index.ts
Labels: ✨ Feature, 🔨 Refactor

#108 feat(#103): 스플래시 스와이퍼 작업
  src/components/TeaCard/SplashSwiper.tsx
  src/components/TeaCard/TeaRecommendSwiper.tsx
  src/stories/HomeReviewCard.stories.tsx
  src/stories/SplashSwiper.stories.tsx
  src/stories/TeaDescriptionCard.stories.tsx
  src/stories/TeaRecipeCard.stories.tsx
  src/stories/TeaRecommendCard.stories.tsx
  src/stories/TeaRecommendSwiper.stories.tsx
  src/stories/TeaReviewCard.stories.tsx
Labels: 🎨 HTML&CSS

#110 modify(#109): 디자인시안 변경에 따른 nav 스타일 수정
  src/components/BottomNav.tsx
Labels: ⚜️Design

#114 bugfix(#113): 레이아웃 컴포넌트 생성
  src/App.tsx
  src/components/Layout.tsx
Labels: 🐞 BugFix

#115 feat(65): input 컴포넌트 코드 변경
  src/components/Input/AuthInput.tsx
  src/components/Input/CheckBox.tsx
  src/components/Input/Input.tsx
  src/components/Input/SearchInput.tsx
  src/constants/index.ts
  src/constants/input.ts
  src/utils/isValidCheck.ts
Labels: 🔨 Refactor

#117 design, refactor(#100): 버튼, 라벨 스타일 수정 및 컴포넌트 리팩토링
  src/components/Buttons/Buttons.tsx
  src/components/Labels/Labels.tsx
  src/components/Review/HomeReviewCard.tsx
  src/stories/Buttons.stories.tsx
  src/stories/HomeReviewCard.stories.tsx
  src/stories/Label/Label.stories.tsx
  src/stories/Label/LabelButton.stories.tsx
  src/stories/Labels.stories.tsx
Labels: 🔨 Refactor, ⚒️ Modify, ⚜️Design

#122 modify(116): 중복확인 input 컴포넌트
  src/components/Input/DuplicateCheckInput.tsx
  src/components/Input/Input.tsx
Labels: ⚒️ Modify

#130 feat: 코드 리뷰 수정사항
  src/App.tsx
  src/components/Buttons/Buttons.tsx
  src/components/Input/DuplicateCheckInput.tsx
  src/components/Input/SearchInput.tsx
  src/components/Input/SelectColor.tsx
  src/components/Main/AppBar.tsx
  src/components/Main/BottomNav.tsx
  src/components/Main/Layout.tsx
  src/components/Main/Logo.tsx
  src/components/Review/HomeReviewCard.tsx
  src/components/Review/StarRate.tsx
  src/components/TeaCard/SplashSwiper.tsx
  src/components/TeaCard/TeaDescriptionCard.tsx
  src/components/TeaCard/TeaRecipeCard.tsx
  src/components/TeaCard/TeaRecommendCard.tsx
  src/components/TeaCard/TeaReviewCard.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Recommend/TeaListPage.tsx
  src/pages/Settings/MyPage.tsx
  src/stories/AppBar.stories.tsx
  src/stories/BottomNav.stories.tsx
  src/stories/Label.stories.tsx
  src/stories/LabelButton.stories.tsx
  src/stories/Logo.stories.tsx
Labels: 📃 Docs

#132 refactor(#128): 수색 선택 컴포넌트 리팩토링
  public/assets/starRate.svg
  src/components/Main/Layout.tsx
  src/components/Select/SelectColor.tsx
  src/stories/SelectColor.stories.tsx
Labels: 🔨 Refactor

#133 refactor(#131): 티카드 리팩토링
  src/components/TeaCard/TeaRecommendCard.tsx
  src/components/TeaCard/TeaReviewCard.tsx
Labels: 🔨 Refactor

#136 refactor(#134, #121): 버튼, 라벨, 홈 리뷰 컴포넌트 리팩토링
  src/components/Buttons/Buttons.tsx
  src/components/Labels/Labels.tsx
  src/components/Review/HomeReviewCard.tsx
  src/stories/Buttons.stories.tsx
  src/stories/HomeReviewCard.stories.tsx
  src/stories/Label.stories.tsx
Labels: 🔨 Refactor, 🥰 Accessibility, ⚜️Design

#143 feat(#142): 라벨그룹 컴포넌트 작업
  src/components/Labels/LabelGroup.tsx
Labels: ✨ Feature

#146 refactor(#144): 별점 컴포넌트 리팩토링
  src/components/Review/StarRate.tsx
Labels: ✨ Feature, 🔨 Refactor

#140 refactor(#139): 라우터 재설정
  src/App.tsx
Labels: 🔨 Refactor

#141 refactor(#131): 카드 컴포넌트 리-리팩토링
  src/components/TeaCard/CardComponents.tsx
  src/stories/TeaDescriptionCard.stories.tsx
  src/stories/TeaRecipeCard.stories.tsx
  src/stories/TeaRecommendCard.stories.tsx
  src/stories/TeaRecommendSwiper.stories.tsx
  src/stories/TeaReviewCard.stories.tsx
Labels: 🔨 Refactor

#137 feature(#124): UserStatus 컴포넌트 구현
  src/components/User/UserStatus.tsx
  src/stories/UserStatus.stories.tsx
Labels: 🎨 HTML&CSS

#147 feature(#127): TabButton 컴포넌트 구현
  src/components/Buttons/TabButton.tsx
  src/stories/TabButton.stories.tsx
Labels: 🎨 HTML&CSS

#150 modify(#152): logo 코드리뷰 수정
  src/components/Main/Logo.tsx
Labels: ⚒️ Modify

#138 feature(#126): TeaBrewingGuide 컴포넌트 구현
  src/components/TeaCard/TeaBrewingGuide.tsx
  src/stories/TeaBrewingGuide.stories.tsx
  tailwind.config.js
Labels: 🎨 HTML&CSS

#145 feat(#120): 리뷰 디테일 페이지 생성
  src/pages/Reviews/ReviewsDetailPage.tsx
Labels: ✨ Feature

#149 modify(#152): app bar 코드리뷰 수정
  src/components/Main/AppBar.tsx
  src/components/Main/Layout.tsx
Labels: 🥰 Accessibility, ⚒️ Modify

#151 modify(#152): bottom nav 코드리뷰 수정
  src/components/Main/BottomNav.tsx
Labels: 🥰 Accessibility, ⚒️ Modify

#169 refactor(135): input 컴포넌트 리팩터링
  src/components/Input/AuthInput.tsx
  src/components/Input/CheckBox.tsx
  src/components/Input/DuplicateCheckInput.tsx
  src/components/Input/Input.tsx
  src/components/Input/SearchInput.tsx
  src/constants/input.ts
  src/styles/globals.css
  src/utils/isValidCheck.ts
  tailwind.config.js
Labels: 🔨 Refactor

#148 feat(123): 검색 필터 버튼 마크업
  src/components/Buttons/SearchFilterButton.tsx
Labels: 🎨 HTML&CSS

#158 modify(#157): 상/하단바 없는 페이지 조건 처리 & 레이아웃 수정
  src/components/Main/Layout.tsx
Labels: ⚒️ Modify

#170 doc(#129): 사용법 주석 추가
  src/components/Labels/LabelGroup.tsx
  src/components/Review/StarRate.tsx
  src/components/Select/SelectColor.tsx
  src/components/TeaCard/CardComponents.tsx
  src/components/TeaCard/SplashSwiper.tsx
  src/components/TeaCard/TeaDescriptionCard.tsx
  src/components/TeaCard/TeaRecipeCard.tsx
  src/components/TeaCard/TeaRecommendCard.tsx
  src/components/TeaCard/TeaRecommendSwiper.tsx
  src/components/TeaCard/TeaReviewCard.tsx
Labels: 📃 Docs

#164 modify(#162): 버튼 컴포넌트 링크 겸용으로 수정
  src/components/Buttons/Buttons.tsx
Labels: ⚒️ Modify, 🎨 HTML&CSS

#168 refactor(#167): 디테일 페이지 버튼 컴포넌트 속성 업데이트
  src/components/Labels/Labels.tsx
  src/pages/Reviews/ReviewsDetailPage.tsx
Labels: 🔨 Refactor

#172 style(#171): 메인에 배경색 지정
  src/components/Main/Layout.tsx
Labels: ⚜️Design

#174 style(#173): 카드 컴포넌트 폰트 사이즈 반영
  src/components/TeaCard/CardComponents.tsx
Labels: ⚜️Design

#176 review(#175): 스와이퍼 role, aria-label 추가
  src/components/TeaCard/SplashSwiper.tsx
  src/components/TeaCard/TeaRecommendSwiper.tsx
Labels: 🔨 Refactor

#177 refactor: 중복코드 리팩토링
  src/components/Main/BottomNav.tsx
Labels: 🔨 Refactor

#181 modify(#180): 버튼 컴포넌트 수정
  src/components/Buttons/Buttons.tsx
Labels: ⚒️ Modify

#179 feature(#156): 추천 티 리스트 페이지 마크업
  src/pages/Recommend/TeaListPage.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#178 feature(#155): 마이페이지 마크업 및 UserCollection 컴포넌트 구현
  src/components/Main/Layout.tsx
  src/components/User/UserActivity.tsx
  src/components/User/UserCollection.tsx
  src/pages/Settings/MyPage.tsx
  src/stories/UserActivity.stories.tsx
Labels: ✨ Feature, ⚒️ Modify, 🎨 HTML&CSS

#184 refactor(#183): 리뷰 카드 별점 프롭 추가
  public/assets/starRate.svg
  src/components/TeaCard/CardComponents.tsx
Labels: 🔨 Refactor

#186 feature(#154): 티 상세 페이지 마크업
  src/App.tsx
  src/components/Buttons/Buttons.tsx
  src/components/Labels/Labels.tsx
  src/components/TeaCard/TeaBrewingGuide.tsx
  src/components/TeaDetail/TeaInfo.tsx
  src/components/TeaDetail/TeaReviewList.tsx
  src/pages/Recommend/TeaDetailPage.tsx
  src/pages/Recommend/TeaListPage.tsx
Labels: ✨ Feature, 🔨 Refactor, ⚒️ Modify, 🎨 HTML&CSS

#203 bugfix(#202): eslint 오류 해결
  .eslintrc.js
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/components/Select/SelectColor.tsx
Labels: 🐞 BugFix

#199 modify(#198): 멘토링 코드수정
  src/components/Main/BottomNav.tsx
  src/components/Main/Logo.tsx
Labels: ⚒️ Modify

#201 settings(#193): 파비콘 추가
  index.html
  public/assets/favicon.png
Labels: ⚙ Settings

#204 bugfix(#189): 스토리북 builder-vite 오류 해결
  pnpm-lock.yaml
  vite.config.js
Labels: 🐞 BugFix

#206 refactor(#195): LabelGroup에 memo 추가
  src/components/Labels/Labels.tsx
Labels: 🔨 Refactor

#207 modify(#205): search Input 수정 후 사용
  src/components/Input/SearchInput.tsx
  src/components/Main/Layout.tsx
  src/pages/Main/MainPage.tsx
Labels: 🐞 BugFix, ⚒️ Modify

#208 bugfix(#189): builder-vite
  package.json
Labels: 🐞 BugFix

#210 refactor: 로고 리팩토링
  src/components/Main/Logo.tsx
Labels: ⚒️ Modify

#211 BugFix(#188): 스플래시 스와이퍼 상호작용 차단
  src/components/Review/HomeReviewCard.tsx
  src/components/TeaCard/SplashSwiper.tsx
Labels: 🐞 BugFix

#213 feature(#212): 테일윈드 전체 스크린 레이아웃 컴포넌트 클래스 추가
  index.html
  tailwind.config.js
Labels: ⚜️Design

#214 refactor: App.tsx 최적화
  src/App.tsx
  src/components/Main/Layout.tsx
  src/layouts/RootLayout.tsx
  src/main.tsx
  src/pages/Join/MySelectionPage.tsx
  src/pages/Join/MyTastePage.tsx
  src/pages/Join/index.ts
  src/pages/Main/MainPage.tsx
  src/pages/Main/SearchPage.tsx
  src/pages/Main/index.ts
  src/pages/Recommend/TeaDetailPage.tsx
  src/pages/Recommend/TeaListPage.tsx
  src/pages/Recommend/index.ts
  src/pages/Reviews/ReviewsDetailPage.tsx
  src/pages/Reviews/ReviewsEditPage.tsx
  src/pages/Reviews/ReviewsPage.tsx
  src/pages/Reviews/ReviewsWritePage.tsx
  src/pages/Reviews/index.ts
  src/pages/Settings/MyEditPage.tsx
  src/pages/Settings/MyFavoritesPage.tsx
  src/pages/Settings/MyPage.tsx
  src/pages/Settings/MyReviewsPage.tsx
  src/pages/Settings/index.ts
  src/pages/index.ts
  src/router.tsx
  src/styles/flaticon.css
  src/styles/globals.css
  src/styles/main.css
Labels: 🔨 Refactor

#209 feat: 스플래시 페이지
  src/pages/Join/MyTastePage.tsx
Labels: 🎨 HTML&CSS

#216 refactor(215): 앱바 + 바텀 내비게이션 fixed 속성 제거
  src/components/Main/AppBar.tsx
  src/components/Main/BottomNav.tsx
  src/layouts/RootLayout.tsx
Labels: 🔨 Refactor

#217 레이아웃 변경으로 상단바 분리
  src/layouts/RootLayout.tsx
  src/pages/Join/MyTastePage.tsx
  src/pages/Main/MainPage.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#219 design(218): body에 스크롤 안 생기도록 수정
  src/layouts/RootLayout.tsx
Labels: ⚜️Design

#221 modify(#220): 버튼, UserActivity 컴포넌트 className 속성 추가 및 페이지 스타일 수정
  src/components/Buttons/Buttons.tsx
  src/components/Buttons/TabButton.tsx
  src/components/TeaDetail/TeaInfo.tsx
  src/components/User/UserActivity.tsx
  src/pages/Recommend/TeaDetailPage.tsx
  src/pages/Recommend/TeaListPage.tsx
  src/pages/Settings/MyPage.tsx
Labels: 🔨 Refactor, ⚒️ Modify, ⚜️Design

#223 refactor(222): 코드 리팩터링
  src/components/Main/AppBar.tsx
  src/components/Main/AppBarController.tsx
  src/components/Main/BottomNav.tsx
  src/components/Main/BottomNavController.tsx
  src/components/Main/LoadingSpinner.tsx
  src/layouts/RootLayout.tsx
  src/pages/Main/NotFoundPage.tsx
  src/pages/Main/index.ts
  src/router.tsx
  src/styles/fonts.css
  src/styles/globals.css
Labels: 🔨 Refactor

#225 modify(#224): 페이지 마크업 수정 및 경로 수정
  src/components/Main/AppBarController.tsx
  src/components/Main/BottomNavController.tsx
  src/pages/Recommend/TeaDetailPage.tsx
  src/pages/Recommend/TeaListPage.tsx
  src/pages/Settings/MyPage.tsx
  src/router.tsx
  src/styles/fonts.css
Labels: 🔨 Refactor, ⚒️ Modify

#226 feat(163): 회원가입/로그인/검색 페이지 마크업
  src/components/Input/DuplicateCheckInput.tsx
  src/components/Main/Logo.tsx
  src/components/TeaCard/CardComponents.tsx
  src/pages/Join/JoinPage.tsx
  src/pages/Join/LoginPage.tsx
  src/pages/Main/SearchPage.tsx
Labels: 🎨 HTML&CSS

#228 feat(#227): 데이터베이스 연결 함수 fetchData 추가
  package.json
  pnpm-lock.yaml
  src/components/Labels/Labels.tsx
  src/pages/Join/MySelectionPage.tsx
  src/utils/fetchData.ts
Labels: ✨ Feature, 💽 Database

#230 build(229): supabase 설치
  package.json
  pnpm-lock.yaml
Labels: ⚙ Settings

#231 feat(#118): my-selection 페이지
  src/components/Labels/Labels.tsx
  src/pages/Join/MySelectionPage.tsx
Labels: ✨ Feature, 🔨 Refactor, ⚜️Design

#234 feat(#233): 리뷰 디테일 페이지 마크업 작업
  src/components/Labels/Labels.tsx
  src/components/TeaCard/CardComponents.tsx
  src/pages/Reviews/ReviewsDetailPage.tsx
  src/stories/TeaColorCard.stories.tsx
  src/stories/TeaTasteCard.stories.tsx
Labels: 🔨 Refactor, ⚜️Design, 🎨 HTML&CSS

#256 feat(#243): 메인 페이지 마크업
  src/components/Main/AppBar.tsx
  src/pages/Main/MainPage.tsx
  src/styles/globals.css
Labels: ✨ Feature, 🎨 HTML&CSS

#257 feat(#240): 리뷰 수정 페이지 마크업
  src/components/Labels/Labels.tsx
  src/components/TeaCard/CardComponents.tsx
  src/pages/Join/MySelectionPage.tsx
  src/pages/Reviews/ReviewsEditPage.tsx
  src/router.tsx
  src/utils/fetchData.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 HTML&CSS

#258 feat(#245): 내 찜 페이지 마크업
  src/components/Buttons/TabButton.tsx
  src/components/Main/AppBar.tsx
  src/pages/Settings/MyFavoritesPage.tsx
  tailwind.config.js
Labels: 🔨 Refactor, 🎨 HTML&CSS

#259 feat(187): 회원가입 기능 추가
  src/App.tsx
  src/api/supabase.ts
  src/components/Input/AuthInput.tsx
  src/components/Input/SearchInput.tsx
  src/pages/Join/JoinPage.tsx
  src/styles/globals.css
Labels: ✨ Feature, 📬 API

#260 feat(165): 로그인 기능 추가
  src/pages/Join/LoginPage.tsx
Labels: ✨ Feature, 📬 API

#262 style(261): 당신의 취향 스플래쉬 페이지 스타일링 수정
  src/pages/Join/JoinPage.tsx
  src/pages/Join/LoginPage.tsx
  src/pages/Join/MyTastePage.tsx
  src/pages/Main/NotFoundPage.tsx
  src/styles/globals.css
Labels: ⚜️Design

#263 feature(#247): 추천 티 리스트 페이지 수정
  src/components/Buttons/TabButton.tsx
  src/components/TeaCard/CardComponents.tsx
  src/pages/Recommend/TeaListPage.tsx
Labels: ✨ Feature

#266 modify(#265), feature(#249): 앱바, 바텀 내비 동적 경로 처리 못하는 문제 수정 및 앱바 로고 버튼 기능 삭제 / 티 상세 페이지 데이터베이스 연결
  src/components/Main/AppBar.tsx
  src/components/Main/AppBarController.tsx
  src/components/Main/BottomNavController.tsx
  src/components/TeaDetail/TeaInfo.tsx
  src/hooks/useTeaData.ts
  src/pages/Recommend/TeaDetailPage.tsx
  src/utils/fetchData.ts
Labels: ✨ Feature, 🔨 Refactor, ⚒️ Modify

#268 feat(#267): 메인 페이지 데이터 추가
  src/components/TeaCard/CardComponents.tsx
  src/components/TeaCard/SplashSwiper.tsx
  src/components/TeaCard/TeaRecommendSwiper.tsx
  src/pages/Main/MainPage.tsx
  src/utils/fetchData.ts
Labels: ✨ Feature, 🔨 Refactor, 💽 Database

#269 feat(#246): 나의 찜 페이지 데이터 연결
  src/pages/Settings/MyFavoritesPage.tsx
Labels: ✨ Feature, 💽 Database

#270 feat(238): 마이페이지 수정 마크업
  src/pages/Settings/MyEditPage.tsx
Labels: 🎨 HTML&CSS

#271 feat(264): 회원가입, 로그인, 로그아웃 기능 및 함수, 스타일링 코드 수정
  src/components/Input/AuthInput.tsx
  src/components/Input/CheckBox.tsx
  src/components/Input/DuplicateCheckInput.tsx
  src/components/Input/DuplicateEmailInput.tsx
  src/components/Input/DuplicateNicknameInput.tsx
  src/components/Input/Input.tsx
  src/constants/input.ts
  src/pages/Join/JoinPage.tsx
  src/pages/Join/LoginPage.tsx
  src/pages/Settings/MyPage.tsx
  src/stores/index.ts
  src/stores/useJoinStore.ts
  src/styles/globals.css
  src/utils/checkDuplicate.ts
  src/utils/index.ts
  src/utils/isValidCheck.ts
  src/utils/userJoin.ts
Labels: 🐞 BugFix, ✨ Feature, 📬 API, 🔨 Refactor, ⚒️ Modify

#273 modify(#272): 루트 경로로 접속 시 로그인 페이지로 리다이렉션 되도록 경로 수정
  src/components/Main/AppBarController.tsx
  src/components/Main/BottomNav.tsx
  src/components/Main/BottomNavController.tsx
  src/pages/Join/LoginPage.tsx
  src/pages/Join/MyTastePage.tsx
  src/pages/Settings/MyEditPage.tsx
  src/router.tsx
Labels: ⚒️ Modify

#275 feature(#248, #251, #253): 마이페이지, 티 리뷰 리스트, 내 리뷰 리스트 페이지 review 데이터베이스 연결
  src/pages/Join/LoginPage.tsx
  src/pages/Reviews/ReviewsPage.tsx
  src/pages/Settings/MyPage.tsx
  src/pages/Settings/MyReviewsPage.tsx
  src/utils/fetchData.ts
Labels: ✨ Feature, 💽 Database

#277 feature(#274): 티 디테일 페이지 리뷰 데이터 연결 및 평점 평균 출력
  src/components/TeaDetail/TeaInfo.tsx
  src/components/TeaDetail/TeaReviewList.tsx
  src/pages/Recommend/TeaDetailPage.tsx
  src/utils/calculateAverageRate.ts
  src/utils/fetchData.ts
Labels: ✨ Feature, ⚒️ Modify

#278 modify(#276): 홈 리뷰 카드 프로필 이미지 -> 티 이미지 수정
  src/components/Review/HomeReviewCard.tsx
  src/pages/Reviews/ReviewsPage.tsx
  src/pages/Settings/MyPage.tsx
  src/pages/Settings/MyReviewsPage.tsx
Labels: ✨ Feature, ⚒️ Modify

#280 feat(#242): 리뷰 디테일 페이지 데이터베이스 연결
  src/components/Review/HomeReviewCard.tsx
  src/components/Select/SelectColor.tsx
  src/components/TeaCard/CardComponents.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Reviews/ReviewsDetailPage.tsx
  src/router.tsx
  src/utils/fetchData.ts
Labels: ✨ Feature, 🔨 Refactor, 💽 Database

#281 feat(#255): 기본 meta 태그 추가
  index.html
Labels: 🥰 Accessibility

#282 feat(#232): 내 취향 선택 페이지 데이터베이스 연결
  src/pages/Join/MySelectionPage.tsx
  src/utils/fetchData.ts
  src/utils/postData.ts
Labels: ✨ Feature, 🔨 Refactor, 💽 Database

#285 feat(237): 검색 기능 구현
  src/components/Buttons/SearchFilterButton.tsx
  src/components/Input/SearchInput.tsx
  src/components/Search/SearchCount.tsx
  src/components/Search/SearchMessage.tsx
  src/hooks/useInputFocus.ts
  src/pages/Main/SearchPage.tsx
  src/utils/getSearchReviewData.ts
  src/utils/getSearchTeaData.ts
Labels: ✨ Feature, 📬 API

#286 feat(#241): 리뷰 수정 페이지 추가
  src/components/Main/BottomNav.tsx
  src/components/Select/SelectColor.tsx
  src/components/TeaCard/CardComponents.tsx
  src/pages/Reviews/ReviewsDetailPage.tsx
  src/pages/Reviews/ReviewsEditPage.tsx
  src/router.tsx
  src/styles/globals.css
  src/utils/updateData.ts
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor, 💽 Database

#290 feature(#279): 찜 기능 구현 및 fetchReviewData 수정으로 인한 페이지 코드 수정
  src/components/Buttons/Buttons.tsx
  src/components/TeaCard/CardComponents.tsx
  src/components/TeaDetail/TeaInfo.tsx
  src/hooks/useTeaLikes.ts
  src/pages/Recommend/TeaDetailPage.tsx
  src/pages/Recommend/TeaListPage.tsx
  src/pages/Reviews/ReviewsDetailPage.tsx
  src/pages/Settings/MyFavoritesPage.tsx
  src/pages/Settings/MyPage.tsx
  src/pages/Settings/MyReviewsPage.tsx
  src/utils/fetchData.ts
  src/utils/likeData.ts
Labels: 🐞 BugFix, ✨ Feature, ⚒️ Modify, 💽 Database

#292 feat: my-taste 기능 추가
  src/components/TeaCard/SplashSwiper.tsx
  src/pages/Join/MyTastePage.tsx
Labels: ✨ Feature

#294 feat(#244): 메인 페이지 기능 구현
  src/pages/Main/MainPage.tsx
Labels: ✨ Feature, 🔨 Refactor

#298 feat(#283): 로그인 시 내 취향 선택 데이터 확인 코드 추가
  src/pages/Join/LoginPage.tsx
Labels: ✨ Feature, 🔨 Refactor

#300 refactor(#296): 리뷰 디테일 페이지 미노출 이슈 체크
  src/components/TeaCard/CardComponents.tsx
  src/pages/Recommend/TeaDetailPage.tsx
  src/pages/Reviews/ReviewsDetailPage.tsx
  src/pages/Reviews/ReviewsWritePage.tsx
  src/router.tsx
  src/utils/createData.ts
  src/utils/fetchData.ts
Labels: 🐞 BugFix, 🔨 Refactor

#301 refactor(#296): 리뷰 수정 페이지 이슈 수정
  src/pages/Reviews/ReviewsEditPage.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#303 refactor(#296): 메인 페이지 이슈 해결
  src/pages/Main/MainPage.tsx
  src/utils/fetchData.ts
Labels: 🐞 BugFix, 🔨 Refactor

#305 refactor(#287): 티 리뷰 작성 페이지 리팩토링
  src/components/TeaDetail/TeaReviewList.tsx
  src/pages/Recommend/TeaDetailPage.tsx
  src/pages/Reviews/ReviewsWritePage.tsx
  src/router.tsx
  src/utils/fetchData.ts
Labels: ✨ Feature, 🔨 Refactor

#306 refactor(#299): 별점 컴포넌트 리팩토링
  src/components/Review/StarRate.tsx
  src/utils/calculateAverageRate.ts
Labels: 🔨 Refactor

#308 refactor(#296): 추천 티 리스트 오류 수정
  src/components/Buttons/TabButton.tsx
  src/hooks/useTeaLikes.ts
  src/pages/Recommend/TeaListPage.tsx
  src/utils/fetchData.ts
Labels: 🐞 BugFix, 🔨 Refactor

#309 refactor(#289): 바텀내브 위로 수색 선택 올라오는 버그 수정
  src/components/Main/BottomNav.tsx
  src/components/TeaCard/CardComponents.tsx
  src/components/TeaCard/TeaRecommendSwiper.tsx
  src/pages/Main/MainPage.tsx
  src/styles/globals.css
Labels: 🐞 BugFix

#313 refactor(#311): 홈 리뷰 카드 리팩토링
  src/components/Review/HomeReviewCard.tsx
  src/components/Review/StarRate.tsx
Labels: 🔨 Refactor

#312 refactor(#311): 별점 컴포넌트 리뷰 수정 페이지에 반영
  src/pages/Reviews/ReviewsDetailPage.tsx
  src/pages/Reviews/ReviewsEditPage.tsx
  src/utils/fetchData.ts
Labels: 🐞 BugFix, 🔨 Refactor

#315 feat(239): 마이페이지 수정(프로필 이미지/닉네임/이메일/비밀번호 변경) 기능
  src/components/Input/DoublePasswordInput.tsx
  src/components/User/UserData.tsx
  src/components/User/UserDataLayout.tsx
  src/components/User/UserProfileImg.tsx
  src/hooks/useLocalStorageUserData.ts
  src/pages/Main/SearchPage.tsx
  src/pages/Settings/MyEditEmailPage.tsx
  src/pages/Settings/MyEditNicknamePage.tsx
  src/pages/Settings/MyEditPage.tsx
  src/pages/Settings/MyEditPasswordPage.tsx
  src/pages/Settings/MyPage.tsx
  src/router.tsx
  src/stores/useJoinStore.ts
  src/utils/updateLocalData.ts
Labels: ✨ Feature, 📬 API

#317 feat(236): 당신의 취향 스플래쉬 기능
  src/pages/Join/MyTastePage.tsx
Labels: ✨ Feature, ⚒️ Modify

#318 modify(#291): fetchData 수정으로 인한 페이지 오류 수정 및 메인페이지, 검색페이지에 티 추천 카드 찜 기능 적용
  src/components/TeaCard/CardComponents.tsx
  src/components/TeaCard/TeaRecommendSwiper.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Main/SearchPage.tsx
  src/pages/Recommend/TeaDetailPage.tsx
  src/pages/Reviews/ReviewsDetailPage.tsx
  src/pages/Reviews/ReviewsEditPage.tsx
  src/pages/Reviews/ReviewsPage.tsx
  src/pages/Settings/MyPage.tsx
  src/pages/Settings/MyReviewsPage.tsx
  src/types/types.ts
  src/utils/fetchData.ts
  src/utils/likeData.ts
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor, ⚒️ Modify, 💽 Database

#338 feat(316): Helmet 컴포넌트 생성
  index.html
  src/components/Main/AppHelmet.tsx
Labels: 🥰 Accessibility

#339 design(337): toast 메시지 출력 위치 수정
  src/App.tsx
Labels: ⚜️Design

#341 refactor(#340): axios 방식 -> 클라이언트 방식
  src/utils/likeData.ts
Labels: 🐞 BugFix, 🔨 Refactor

#342 refactor(#336, #334): 메인 티 데이터 필터링 개수 제한
  src/components/Review/HomeReviewCard.tsx
  src/components/TeaCard/CardComponents.tsx
  src/components/TeaCard/TeaBrewingGuide.tsx
  src/components/TeaDetail/TeaReviewList.tsx
  src/components/User/UserCollection.tsx
  src/components/User/UserData.tsx
  src/pages/Join/MySelectionPage.tsx
  src/pages/Join/MyTastePage.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Recommend/TeaDetailPage.tsx
  src/pages/Reviews/ReviewsWritePage.tsx
  src/pages/Settings/MyPage.tsx
Labels: 🔨 Refactor

#343 bugfix(#335): 헤딩맵 사용 시 레이아웃 틀어지는 현상 수정
  src/components/Main/AppBar.tsx
  src/components/Main/BottomNav.tsx
  src/pages/Main/MainPage.tsx
  src/styles/globals.css
Labels: 🔨 Refactor

#344 refactor(#331): 티 데이터 필터링 추가 수정 및 티 리뷰 카드 리팩토링
  src/components/Review/HomeReviewCard.tsx
  src/components/TeaCard/CardComponents.tsx
  src/pages/Main/MainPage.tsx
  src/utils/fetchData.ts
Labels: 🔨 Refactor

#349 bugfix(#348): 로딩 중 내브바 위치 이동 이슈 수정
  src/components/Main/LoadingSpinner.tsx
Labels: 🐞 BugFix

#350 refactor(#329, #323, #324): 추천 티 리스트 카드 컴포넌트 수정
  src/components/TeaCard/CardComponents.tsx
  src/pages/Recommend/TeaListPage.tsx
  src/styles/globals.css
Labels: 🔨 Refactor

#351 refactor(#321, #330, #325): 티 리뷰 수정
  src/components/Select/SelectColor.tsx
  src/components/TeaCard/CardComponents.tsx
  src/components/TeaDetail/TeaReviewList.tsx
  src/pages/Recommend/TeaDetailPage.tsx
  src/pages/Reviews/ReviewsDetailPage.tsx
  src/pages/Reviews/ReviewsEditPage.tsx
  src/pages/Reviews/ReviewsWritePage.tsx
  src/utils/fetchData.ts
Labels: 🔨 Refactor

#357 feature(#314): 전체 티 보기 기능 구현
  src/components/Review/HomeReviewCard.tsx
  src/pages/Recommend/TeaListPage.tsx
  src/pages/Reviews/ReviewsPage.tsx
  src/pages/Settings/MyReviewsPage.tsx
  src/types/types.ts
Labels: ✨ Feature
